name: Setup Terragrunt
description: Action to setup terragrunt

inputs:
  version:
    description: Terragrunt version to install
    required: false
  token:
    description: Github token
    required: false
    default: ${{ github.token }}
  install_wrapper:
    description: Flag to install Wrapper CLI
    required: false
    default: 'true'

outputs:
  version:
    description: Installed Terragrunt version

runs:
  using: node16
  main: dist/index.js
