name: Test Action

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
      - ".gitignore"

concurrency: ${{ github.ref }}

jobs:
  test-1:
    name: Latest version
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup terragrunt
        uses: ./

      - name: Check terragrunt version
        run: terragrunt -version

  test-2:
    name: Specific version
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup terragrunt
        uses: ./
        with:
          version: 0.38.10

      - name: Check terragrunt version
        run: terragrunt -version

  test-3:
    name: Specific version already installed
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup terragrunt
        uses: ./
        with:
          version: 0.38.10

      - name: Setup terragrunt
        uses: ./
        with:
          version: 0.38.10

      - name: Check terragrunt version
        run: terragrunt -version
